### ISSUE TITLE
V2 Roadmap

### ISSUE THREAD

**Issue by Smaug6739** [Smaug6739/Alexandrie#1]
# V2 Roadmap

## Client V2

- [x] Use nuxt framework
- [x] Bump Nuxt to rc.10
- [x] PWA Support
- [x] Improve performances
- [x] Refactor state (remove double fetch and use getters) (in progress) 
- [x] Fix typo
- [x] General
  - [x] Improve Middleware Auth (use Cookies) 
  - [x] Refactor components with setup (composition API) 
- [x] Theme
  - [x] White theme
  - [x] Save theme on localStorage or cookie
  - [x] New containers
- [x] Layout
  - [x] Sidebar
    - [x] Links bubles
    - [x] improve responsive design
  - [x] Table content 
  - [x] Footer
- [x] Pages
  - [x] Bubbles on links
  - [x] Responsive design 
  - [x] Admin dashboard improve home page
  - [x] Admin dashboard backup
  - [x] Admin dashboard improve CDN
  - [x] Improve DataTable
  - [x] Improve MarkdownEditor
  - [x] Padding on images
- [x] Features
  - [x] Refresh state button
  - [x] Edit page button
- [x] Code
  - [x] Reorganize markdown compilation

## Backend

- [x] Use Sequelize ORM
- [x] Refactor JWT automatic regenerate
