### ISSUE TITLE
V4 Roadmap

### ISSUE THREAD

**Issue by Smaug6739** [Smaug6739/Alexandrie#4]
# V4 Roadmap :rocket: 

## Frontend

- [x] Refactor home page to allow navigation to categories
- [x] Refactor sidebar to use new icons
- [x] Make it PWA
- [x] Change logo of application
- [x] Use new theme (@alexandrie/styles V4) 
- [x] Add transitions between pages

## Dashboard

- [x] Complete rewrite of dashboard
- [x] Use new theme (@alexandrie/styles V4) 
- [x] New sidebar to simplify navigation
- [x] Display differents categories directly on sidebar
- [x] Add new applications
  - [x] Categories manager
  - [x] CDN with drop feature
  - [x] Backup
- [x] Add transitions between pages
- [x] Reorganize SCSS and JS code
  - [ ] Put rules in alphabetical order
  - [ ] Reorganize classes / selectors
  - [ ] Remove unnecessary rules
  - [ ] Put in an unique file reused rules
  - [ ] Organize JS by blocks and add comments
  - [ ] Organise html by blocks and add comments
  - [ ] Split components in differents components

## Other

- [x] Change the format of Article: => Document. Add properties like tags, options etc.
- [x] Change the category system. One table only and a column `parent_id`
- [x] Migrate old data to new database
- [x] Remove old icons system and use svg

## Github CI/CD

- [x] Compile on server
- [x] New automatic deployment
