### ISSUE TITLE
V5 Roadmap

### ISSUE THREAD

**Issue by Smaug6739** [Smaug6739/Alexandrie#5]
# V5 Roadmap :rocket:

## Dashboard

- [ ] Refactor home page
- [ ] Refactor login page
- [ ] Change logo of application
- [ ] New file system
- [ ] New CDN system (manage, edit, delete)

## Styles

- [ ] Code block
- [ ] Fix navbar spaces on mobile
- [ ] Improve motifications design
- [ ] Dashboard add back to top component
- [ ] Improve modal design

## Dashboard

- [ ] Close sidebar on mobile click
- [ ] Rewrite backdrop ?
- [ ] "Add item" with default picture
- [ ] "+" button after hover file
- [ ] Category dropdown selector
- [ ] New markdown editor + dynamic
- [ ] Change categories to workspaces
- [ ] Reorganize SCSS and JS code
  - [ ] Put rules in alphabetical order
  - [ ] Reorganize classes / selectors
  - [ ] Remove unnecessary rules
  - [ ] Put in an unique file reused rules
  - [ ] Organize JS by blocks and add comments
  - [ ] Organise html by blocks and add comments
  - [ ] Split components in differents components

## Other

- [x] Change the format of Article: => Document. Add properties like tags, options etc.
- [x] Change the category system. One table only and a column `parent_id`
- [x] Migrate old data to new database
- [x] Remove old icons system and use svg

## Github CI/CD

- [x] Switch to bun
- [ ] Improve workflox file
