### ISSUE TITLE
Version 7.0.0 roadmap

### ISSUE THREAD

**Issue by Smaug6739** [Smaug6739/Alexandrie#7]
# Version 7.0.0 roadmap 🚀

## Dashboard 

- [ ] Create an admin dashboard to separate frontend app and admin functions
- [ ] Add users manager
- [ ] Add documents manager 
- [ ] Add statistics page view

## Frontend

- [x] Add perferences settings for user
- [ ] Add security functions (see actives sessions for example)
- [ ] Add delete account function
- [ ] Improve performances 

## Backend

- [ ] Add a cache system
- [ ] Delete old avatar files
- [ ] Add a new permissions system based on roles and permissions with bitfield
